/*******************************************************************************************
*  This class is autogenerated from the class TitleServiceLogger
*  Do not directly update this class as changes will be lost on rebuild.
*******************************************************************************************/
using System;
using System.Diagnostics.Tracing;
using System.Threading.Tasks;

namespace TitleService
{
	internal sealed partial class TitleServiceEventSource
	{

		private const int UpdateTitleEventId = 2001;

		[Event(UpdateTitleEventId, Level = EventLevel.LogAlways, Message = "Update Title {2} {3}", Keywords = Keywords.TitleService)]
		public void UpdateTitle(
			bool autogenerated, 
			string machineName, 
			string person, 
			string title)
		{
			WriteEvent(
				UpdateTitleEventId, 
				autogenerated, 
				machineName, 
				person, 
				title);
		}


	}
}