/*******************************************************************************************
*  This class is autogenerated from the class CommunicationLogger
*  Do not directly update this class as changes will be lost on rebuild.
*******************************************************************************************/
using System;
using System.Diagnostics.Tracing;
using System.Threading.Tasks;

namespace TitleService
{
	internal sealed partial class TitleServiceEventSource
	{

		private const int StartRecieveServiceMessageEventId = 1001;

		[Event(StartRecieveServiceMessageEventId, Level = EventLevel.LogAlways, Message = "Start Recieve Service Message {2} {3} {4} {5}", Keywords = Keywords.Communication, Opcode = EventOpcode.Start, Task = Tasks.RecieveServiceMessage)]
		private void StartRecieveServiceMessage(
			bool autogenerated, 
			string machineName, 
			string requestUri, 
			string serviceMethodName, 
			string serviceMessageHeaders, 
			string customServiceRequestHeader)
		{
			WriteEvent(
				StartRecieveServiceMessageEventId, 
				autogenerated, 
				machineName, 
				requestUri, 
				serviceMethodName, 
				serviceMessageHeaders, 
				customServiceRequestHeader);
		}

		[NonEvent]
		public void StartRecieveServiceMessage(
			bool autogenerated, 
			string machineName, 
			System.Uri requestUri, 
			string serviceMethodName, 
			Microsoft.ServiceFabric.Services.Remoting.ServiceRemotingMessageHeaders serviceMessageHeaders, 
			FG.ServiceFabric.Services.Remoting.FabricTransport.CustomServiceRequestHeader customServiceRequestHeader)
		{
			if (this.IsEnabled())
			{
				StartRecieveServiceMessage(
					autogenerated, 
					Environment.MachineName, 
					requestUri.ToString(), 
					serviceMethodName, 
					serviceMessageHeaders.ToString(), 
					customServiceRequestHeader.ToString());
			}
		}


		private const int StopRecieveServiceMessageEventId = 2002;

		[Event(StopRecieveServiceMessageEventId, Level = EventLevel.LogAlways, Message = "Stop Recieve Service Message {2} {3} {4} {5}", Keywords = Keywords.Communication, Opcode = EventOpcode.Stop, Task = Tasks.RecieveServiceMessage)]
		private void StopRecieveServiceMessage(
			bool autogenerated, 
			string machineName, 
			string requestUri, 
			string serviceMethodName, 
			string serviceMessageHeaders, 
			string customServiceRequestHeader)
		{
			WriteEvent(
				StopRecieveServiceMessageEventId, 
				autogenerated, 
				machineName, 
				requestUri, 
				serviceMethodName, 
				serviceMessageHeaders, 
				customServiceRequestHeader);
		}

		[NonEvent]
		public void StopRecieveServiceMessage(
			bool autogenerated, 
			string machineName, 
			System.Uri requestUri, 
			string serviceMethodName, 
			Microsoft.ServiceFabric.Services.Remoting.ServiceRemotingMessageHeaders serviceMessageHeaders, 
			FG.ServiceFabric.Services.Remoting.FabricTransport.CustomServiceRequestHeader customServiceRequestHeader)
		{
			if (this.IsEnabled())
			{
				StopRecieveServiceMessage(
					autogenerated, 
					Environment.MachineName, 
					requestUri.ToString(), 
					serviceMethodName, 
					serviceMessageHeaders.ToString(), 
					customServiceRequestHeader.ToString());
			}
		}


		private const int RecieveServiceMessageFailedEventId = 3003;

		[Event(RecieveServiceMessageFailedEventId, Level = EventLevel.LogAlways, Message = "{6}", Keywords = Keywords.Communication)]
		private void RecieveServiceMessageFailed(
			bool autogenerated, 
			string machineName, 
			string requestUri, 
			string serviceMethodName, 
			string serviceMessageHeaders, 
			string customServiceRequestHeader, 
			string message, 
			string source, 
			string exceptionTypeName, 
			string exception)
		{
			WriteEvent(
				RecieveServiceMessageFailedEventId, 
				autogenerated, 
				machineName, 
				requestUri, 
				serviceMethodName, 
				serviceMessageHeaders, 
				customServiceRequestHeader, 
				message, 
				source, 
				exceptionTypeName, 
				exception);
		}

		[NonEvent]
		public void RecieveServiceMessageFailed(
			bool autogenerated, 
			string machineName, 
			System.Uri requestUri, 
			string serviceMethodName, 
			Microsoft.ServiceFabric.Services.Remoting.ServiceRemotingMessageHeaders serviceMessageHeaders, 
			FG.ServiceFabric.Services.Remoting.FabricTransport.CustomServiceRequestHeader customServiceRequestHeader, 
			System.Exception ex)
		{
			if (this.IsEnabled())
			{
				RecieveServiceMessageFailed(
					autogenerated, 
					Environment.MachineName, 
					requestUri.ToString(), 
					serviceMethodName, 
					serviceMessageHeaders.ToString(), 
					customServiceRequestHeader.ToString(), 
					ex.Message, 
					ex.Source, 
					ex.GetType().FullName, 
					ex.AsJson());
			}
		}


		private const int FailedToGetServiceMethodNameEventId = 4004;

		[Event(FailedToGetServiceMethodNameEventId, Level = EventLevel.LogAlways, Message = "{5}", Keywords = Keywords.Communication)]
		private void FailedToGetServiceMethodName(
			bool autogenerated, 
			string machineName, 
			string requestUri, 
			int interfaceId, 
			int methodId, 
			string message, 
			string source, 
			string exceptionTypeName, 
			string exception)
		{
			WriteEvent(
				FailedToGetServiceMethodNameEventId, 
				autogenerated, 
				machineName, 
				requestUri, 
				interfaceId, 
				methodId, 
				message, 
				source, 
				exceptionTypeName, 
				exception);
		}

		[NonEvent]
		public void FailedToGetServiceMethodName(
			bool autogenerated, 
			string machineName, 
			System.Uri requestUri, 
			int interfaceId, 
			int methodId, 
			System.Exception ex)
		{
			if (this.IsEnabled())
			{
				FailedToGetServiceMethodName(
					autogenerated, 
					Environment.MachineName, 
					requestUri.ToString(), 
					interfaceId, 
					methodId, 
					ex.Message, 
					ex.Source, 
					ex.GetType().FullName, 
					ex.AsJson());
			}
		}


		private const int StartRequestContextEventId = 5005;

		[Event(StartRequestContextEventId, Level = EventLevel.LogAlways, Message = "Start Request Context {2}", Keywords = Keywords.Communication, Opcode = EventOpcode.Start)]
		private void StartRequestContext(
			bool autogenerated, 
			string machineName, 
			string headers)
		{
			WriteEvent(
				StartRequestContextEventId, 
				autogenerated, 
				machineName, 
				headers);
		}

		[NonEvent]
		public void StartRequestContext(
			bool autogenerated, 
			string machineName, 
			System.Collections.Generic.IEnumerable<FG.ServiceFabric.Services.Remoting.FabricTransport.ServiceRequestHeader> headers)
		{
			if (this.IsEnabled())
			{
				StartRequestContext(
					autogenerated, 
					Environment.MachineName, 
					headers.ToString());
			}
		}


		private const int StopRequestContextEventId = 6006;

		[Event(StopRequestContextEventId, Level = EventLevel.LogAlways, Message = "Stop Request Context {2}", Keywords = Keywords.Communication, Opcode = EventOpcode.Stop)]
		private void StopRequestContext(
			bool autogenerated, 
			string machineName, 
			string headers)
		{
			WriteEvent(
				StopRequestContextEventId, 
				autogenerated, 
				machineName, 
				headers);
		}

		[NonEvent]
		public void StopRequestContext(
			bool autogenerated, 
			string machineName, 
			System.Collections.Generic.IEnumerable<FG.ServiceFabric.Services.Remoting.FabricTransport.ServiceRequestHeader> headers)
		{
			if (this.IsEnabled())
			{
				StopRequestContext(
					autogenerated, 
					Environment.MachineName, 
					headers.ToString());
			}
		}


		private const int FailedRequestContextEventId = 7007;

		[Event(FailedRequestContextEventId, Level = EventLevel.LogAlways, Message = "{3}", Keywords = Keywords.Communication)]
		private void FailedRequestContext(
			bool autogenerated, 
			string machineName, 
			string headers, 
			string message, 
			string source, 
			string exceptionTypeName, 
			string exception)
		{
			WriteEvent(
				FailedRequestContextEventId, 
				autogenerated, 
				machineName, 
				headers, 
				message, 
				source, 
				exceptionTypeName, 
				exception);
		}

		[NonEvent]
		public void FailedRequestContext(
			bool autogenerated, 
			string machineName, 
			System.Collections.Generic.IEnumerable<FG.ServiceFabric.Services.Remoting.FabricTransport.ServiceRequestHeader> headers, 
			System.Exception exception)
		{
			if (this.IsEnabled())
			{
				FailedRequestContext(
					autogenerated, 
					Environment.MachineName, 
					headers.ToString(), 
					exception.Message, 
					exception.Source, 
					exception.GetType().FullName, 
					exception.AsJson());
			}
		}


		private const int FailedToReadCustomServiceMessageHeaderEventId = 8008;

		[Event(FailedToReadCustomServiceMessageHeaderEventId, Level = EventLevel.LogAlways, Message = "{3}", Keywords = Keywords.Communication)]
		private void FailedToReadCustomServiceMessageHeader(
			bool autogenerated, 
			string machineName, 
			string serviceRemotingMessageHeaders, 
			string message, 
			string source, 
			string exceptionTypeName, 
			string exception)
		{
			WriteEvent(
				FailedToReadCustomServiceMessageHeaderEventId, 
				autogenerated, 
				machineName, 
				serviceRemotingMessageHeaders, 
				message, 
				source, 
				exceptionTypeName, 
				exception);
		}

		[NonEvent]
		public void FailedToReadCustomServiceMessageHeader(
			bool autogenerated, 
			string machineName, 
			Microsoft.ServiceFabric.Services.Remoting.ServiceRemotingMessageHeaders serviceRemotingMessageHeaders, 
			System.Exception ex)
		{
			if (this.IsEnabled())
			{
				FailedToReadCustomServiceMessageHeader(
					autogenerated, 
					Environment.MachineName, 
					serviceRemotingMessageHeaders.ToString(), 
					ex.Message, 
					ex.Source, 
					ex.GetType().FullName, 
					ex.AsJson());
			}
		}


		private const int EnumeratingPartitionsEventId = 9009;

		[Event(EnumeratingPartitionsEventId, Level = EventLevel.LogAlways, Message = "Enumerating Partitions {2}", Keywords = Keywords.Communication)]
		private void EnumeratingPartitions(
			bool autogenerated, 
			string machineName, 
			string serviceUri)
		{
			WriteEvent(
				EnumeratingPartitionsEventId, 
				autogenerated, 
				machineName, 
				serviceUri);
		}

		[NonEvent]
		public void EnumeratingPartitions(
			bool autogenerated, 
			string machineName, 
			System.Uri serviceUri)
		{
			if (this.IsEnabled())
			{
				EnumeratingPartitions(
					autogenerated, 
					Environment.MachineName, 
					serviceUri.ToString());
			}
		}


		private const int FailedToEnumeratePartitionsEventId = 10010;

		[Event(FailedToEnumeratePartitionsEventId, Level = EventLevel.LogAlways, Message = "{3}", Keywords = Keywords.Communication)]
		private void FailedToEnumeratePartitions(
			bool autogenerated, 
			string machineName, 
			string serviceUri, 
			string message, 
			string source, 
			string exceptionTypeName, 
			string exception)
		{
			WriteEvent(
				FailedToEnumeratePartitionsEventId, 
				autogenerated, 
				machineName, 
				serviceUri, 
				message, 
				source, 
				exceptionTypeName, 
				exception);
		}

		[NonEvent]
		public void FailedToEnumeratePartitions(
			bool autogenerated, 
			string machineName, 
			System.Uri serviceUri, 
			System.Exception ex)
		{
			if (this.IsEnabled())
			{
				FailedToEnumeratePartitions(
					autogenerated, 
					Environment.MachineName, 
					serviceUri.ToString(), 
					ex.Message, 
					ex.Source, 
					ex.GetType().FullName, 
					ex.AsJson());
			}
		}


		private const int EnumeratedExistingPartitionsEventId = 11011;

		[Event(EnumeratedExistingPartitionsEventId, Level = EventLevel.LogAlways, Message = "Enumerated Existing Partitions {2} {3}", Keywords = Keywords.Communication)]
		private void EnumeratedExistingPartitions(
			bool autogenerated, 
			string machineName, 
			string serviceUri, 
			string partitions)
		{
			WriteEvent(
				EnumeratedExistingPartitionsEventId, 
				autogenerated, 
				machineName, 
				serviceUri, 
				partitions);
		}

		[NonEvent]
		public void EnumeratedExistingPartitions(
			bool autogenerated, 
			string machineName, 
			System.Uri serviceUri, 
			System.Collections.Generic.IEnumerable<System.Fabric.ServicePartitionInformation> partitions)
		{
			if (this.IsEnabled())
			{
				EnumeratedExistingPartitions(
					autogenerated, 
					Environment.MachineName, 
					serviceUri.ToString(), 
					partitions.ToString());
			}
		}


		private const int EnumeratedAndCachedPartitionsEventId = 12012;

		[Event(EnumeratedAndCachedPartitionsEventId, Level = EventLevel.LogAlways, Message = "Enumerated And Cached Partitions {2} {3}", Keywords = Keywords.Communication)]
		private void EnumeratedAndCachedPartitions(
			bool autogenerated, 
			string machineName, 
			string serviceUri, 
			string partitions)
		{
			WriteEvent(
				EnumeratedAndCachedPartitionsEventId, 
				autogenerated, 
				machineName, 
				serviceUri, 
				partitions);
		}

		[NonEvent]
		public void EnumeratedAndCachedPartitions(
			bool autogenerated, 
			string machineName, 
			System.Uri serviceUri, 
			System.Collections.Generic.IEnumerable<System.Fabric.ServicePartitionInformation> partitions)
		{
			if (this.IsEnabled())
			{
				EnumeratedAndCachedPartitions(
					autogenerated, 
					Environment.MachineName, 
					serviceUri.ToString(), 
					partitions.ToString());
			}
		}


		private const int StartCallServiceEventId = 13013;

		[Event(StartCallServiceEventId, Level = EventLevel.LogAlways, Message = "Start Call Service {2} {3} {4} {5}", Keywords = Keywords.Communication, Opcode = EventOpcode.Start, Task = Tasks.CallService)]
		private void StartCallService(
			bool autogenerated, 
			string machineName, 
			string requestUri, 
			string serviceMethodName, 
			string serviceMessageHeaders, 
			string customServiceRequestHeader)
		{
			WriteEvent(
				StartCallServiceEventId, 
				autogenerated, 
				machineName, 
				requestUri, 
				serviceMethodName, 
				serviceMessageHeaders, 
				customServiceRequestHeader);
		}

		[NonEvent]
		public void StartCallService(
			bool autogenerated, 
			string machineName, 
			System.Uri requestUri, 
			string serviceMethodName, 
			Microsoft.ServiceFabric.Services.Remoting.ServiceRemotingMessageHeaders serviceMessageHeaders, 
			FG.ServiceFabric.Services.Remoting.FabricTransport.CustomServiceRequestHeader customServiceRequestHeader)
		{
			if (this.IsEnabled())
			{
				StartCallService(
					autogenerated, 
					Environment.MachineName, 
					requestUri.ToString(), 
					serviceMethodName, 
					serviceMessageHeaders.ToString(), 
					customServiceRequestHeader.ToString());
			}
		}


		private const int StopCallServiceEventId = 14014;

		[Event(StopCallServiceEventId, Level = EventLevel.LogAlways, Message = "Stop Call Service {2} {3} {4} {5}", Keywords = Keywords.Communication, Opcode = EventOpcode.Stop, Task = Tasks.CallService)]
		private void StopCallService(
			bool autogenerated, 
			string machineName, 
			string requestUri, 
			string serviceMethodName, 
			string serviceMessageHeaders, 
			string customServiceRequestHeader)
		{
			WriteEvent(
				StopCallServiceEventId, 
				autogenerated, 
				machineName, 
				requestUri, 
				serviceMethodName, 
				serviceMessageHeaders, 
				customServiceRequestHeader);
		}

		[NonEvent]
		public void StopCallService(
			bool autogenerated, 
			string machineName, 
			System.Uri requestUri, 
			string serviceMethodName, 
			Microsoft.ServiceFabric.Services.Remoting.ServiceRemotingMessageHeaders serviceMessageHeaders, 
			FG.ServiceFabric.Services.Remoting.FabricTransport.CustomServiceRequestHeader customServiceRequestHeader)
		{
			if (this.IsEnabled())
			{
				StopCallService(
					autogenerated, 
					Environment.MachineName, 
					requestUri.ToString(), 
					serviceMethodName, 
					serviceMessageHeaders.ToString(), 
					customServiceRequestHeader.ToString());
			}
		}


		private const int CallServiceFailedEventId = 15015;

		[Event(CallServiceFailedEventId, Level = EventLevel.LogAlways, Message = "{6}", Keywords = Keywords.Communication)]
		private void CallServiceFailed(
			bool autogenerated, 
			string machineName, 
			string requestUri, 
			string serviceMethodName, 
			string serviceMessageHeaders, 
			string customServiceRequestHeader, 
			string message, 
			string source, 
			string exceptionTypeName, 
			string exception)
		{
			WriteEvent(
				CallServiceFailedEventId, 
				autogenerated, 
				machineName, 
				requestUri, 
				serviceMethodName, 
				serviceMessageHeaders, 
				customServiceRequestHeader, 
				message, 
				source, 
				exceptionTypeName, 
				exception);
		}

		[NonEvent]
		public void CallServiceFailed(
			bool autogenerated, 
			string machineName, 
			System.Uri requestUri, 
			string serviceMethodName, 
			Microsoft.ServiceFabric.Services.Remoting.ServiceRemotingMessageHeaders serviceMessageHeaders, 
			FG.ServiceFabric.Services.Remoting.FabricTransport.CustomServiceRequestHeader customServiceRequestHeader, 
			System.Exception ex)
		{
			if (this.IsEnabled())
			{
				CallServiceFailed(
					autogenerated, 
					Environment.MachineName, 
					requestUri.ToString(), 
					serviceMethodName, 
					serviceMessageHeaders.ToString(), 
					customServiceRequestHeader.ToString(), 
					ex.Message, 
					ex.Source, 
					ex.GetType().FullName, 
					ex.AsJson());
			}
		}


		private const int ServiceClientFailedEventId = 16016;

		[Event(ServiceClientFailedEventId, Level = EventLevel.LogAlways, Message = "{4}", Keywords = Keywords.Communication)]
		private void ServiceClientFailed(
			bool autogenerated, 
			string machineName, 
			string requestUri, 
			string customServiceRequestHeader, 
			string message, 
			string source, 
			string exceptionTypeName, 
			string exception)
		{
			WriteEvent(
				ServiceClientFailedEventId, 
				autogenerated, 
				machineName, 
				requestUri, 
				customServiceRequestHeader, 
				message, 
				source, 
				exceptionTypeName, 
				exception);
		}

		[NonEvent]
		public void ServiceClientFailed(
			bool autogenerated, 
			string machineName, 
			System.Uri requestUri, 
			FG.ServiceFabric.Services.Remoting.FabricTransport.CustomServiceRequestHeader customServiceRequestHeader, 
			System.Exception ex)
		{
			if (this.IsEnabled())
			{
				ServiceClientFailed(
					autogenerated, 
					Environment.MachineName, 
					requestUri.ToString(), 
					customServiceRequestHeader.ToString(), 
					ex.Message, 
					ex.Source, 
					ex.GetType().FullName, 
					ex.AsJson());
			}
		}


	}
}