/*******************************************************************************************
*  This class is autogenerated from the class ServiceFabricPeopleTestsEventSource.eventsource.json
*  Do not directly update this class as changes will be lost on rebuild.
*******************************************************************************************/
using System;
using System.Diagnostics.Tracing;
using System.Threading.Tasks;

namespace ServiceFabricPeople.Tests
{
	[EventSource(Name = "ServiceFabricPeople-Tests")]
	internal sealed partial class ServiceFabricPeopleTestsEventSource : EventSource
	{
		public static readonly ServiceFabricPeopleTestsEventSource Current = new ServiceFabricPeopleTestsEventSource();

		static ServiceFabricPeopleTestsEventSource()
		{
			// A workaround for the problem where ETW activities do not 
			// get tracked until Tasks infrastructure is initialized.
			// This problem will be fixed in .NET Framework 4.6.2.
			Task.Run(() => { });
		}

		// Instance constructor is private to enforce singleton semantics
		private ServiceFabricPeopleTestsEventSource() : base() { }

		#region Keywords
		// Event keywords can be used to categorize events. 
		// Each keyword is a bit flag. A single event can be 
		// associated with multiple keywords (via EventAttribute.Keywords property).
		// Keywords must be defined as a public class named 'Keywords' 
		// inside EventSource that uses them.
		public static class Keywords
		{
			public const EventKeywords Communication = (EventKeywords)0x1L;

		}
		#endregion Keywords

		#region Tasks

		public static class Tasks
		{
			public const EventTask RecieveActorMessage = (EventTask)0x1L;
			public const EventTask RecieveServiceMessage = (EventTask)0x2L;
			public const EventTask CallActor = (EventTask)0x4L;
			public const EventTask CallService = (EventTask)0x8L;

		}
		#endregion Tasks

		#region Events



		#endregion Events
	}


	internal static class ServiceFabricPeopleTestsEventSourceHelpers
	{

            public static string AsJson(this System.Exception that)
            {
                return Newtonsoft.Json.JsonConvert.SerializeObject(that);
            }


	}

}